### ISSUE TITLE
Update README.md for instructions

### ISSUE THREAD

**Issue by nt661974** [harsh317/Python-Keylogger#2]
Update README.md for instructions, since the code is in input mode now. Don't swap the variable lines, as you told to do previously. Convert morse code. --- .--. . -. / ... -.- -.-- .--. . 
Side note bro.

**Comment by harsh317** [comment]
Ya. I forgot. Sorry
What do you mean by 'Convert morse code. --- .--. . -. / ... -.- -.-- .--. .'

**Comment by nt661974** [comment]
Just convert the morse code website for a message. Close the issue.
